/// Flutter icons BookifyIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.

// ignore_for_file: constant_identifier_names

library;

import 'package:flutter/widgets.dart';

class BookifyIcons {
  BookifyIcons._();

  static const _kFontFam = 'BookifyIcons';
  static const String? _kFontPkg = null;

  static const IconData qr_code =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookcase =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookcase_outlined =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData isbn =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
